rails-review/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cat_dogs, only: [:new, :create, :show]
  resources :pet_beds, only: [:show]
end

rails-review/app/models/bed_rental.rb
class BedRental < ActiveRecord::Base
  belongs_to :pet_bed
  belongs_to :cat_dog
end

rails-review/app/models/cat_dog.rb
class CatDog < ActiveRecord::Base
  has_many :poo_bags
  has_many :bed_rentals
  has_many :rented_beds, through: :bed_rentals, source: :pet_bed
end

rails-review/app/models/pet_bed.rb
class PetBed < ActiveRecord::Base
  has_many :bed_rentals
  has_many :cat_dogs, through: :bed_rentals

  def description
    "#{size.capitalize} #{condition.capitalize}"
  end
end

rails-review/app/models/poo_bag.rb
class PooBag < ActiveRecord::Base
  belongs_to :cat_dog
end

rails-review/app/controllers/cat_dogs_controller.rb
class CatDogsController < ApplicationController
  def new
    @cat_dog = CatDog.new
    @pet_beds = PetBed.all
  end

  def create
    c = CatDog.create(cat_dog_params)
    redirect_to cat_dog_path(c)
  end

  def show
    @cat_dog = CatDog.find_by(id: params[:id])

  end

  private

  def cat_dog_params
    params.require(:cat_dog).permit(:name, :age, rented_bed_ids: [])
  end
end

rails-review/app/helpers/cat_dogs_helper.rb
module CatDogsHelper
end

rails-review/app/views/cat_dogs/new.html.erb
<h1>Hello world</h1>

<%= form_with model: @cat_dog do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <br>
  <%= f.label :rented_bed_ids %>
  <%= f.collection_check_boxes :rented_bed_ids, @pet_beds, :id, :description %>

  <%= f.submit %>
<% end %>

rails-review/app/views/cat_dogs/show.html.erb
<h1>TADA!</h1>

<%= @cat_dog.name %>

<h3>My rented beds</h3>

<% @cat_dog.rented_beds.each do |bed| %>
  <%= link_to bed.description, pet_bed_path(bed)  %>
<% end %>

rails-review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>